export const RECEIVE_STRIPS = 'RECEIVE_STRIPS';
export const REQUEST_STRIPS_FAILED = 'REQUEST_STRIPS_FAILED';

export const RECEIVE_STRIP_INFO = 'RECEIVE_STRIP_INFO';
export const REQUEST_STRIPS_INFO_FAILED = 'REQUEST_STRIPS_INFO_FAILED';
